# Generated by Django 3.2.12 on 2022-04-12 11:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import movie_review_project.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(1), movie_review_project.common.validators.validate_only_letters])),
                ('last_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(1), movie_review_project.common.validators.validate_only_letters])),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.moviereviewuser')),
            ],
        ),
        migrations.AddField(
            model_name='moviereviewuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='staticfiles/images/default-profile-picture.jpg', upload_to='mediafiles/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
