# Generated by Django 3.2.12 on 2022-04-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/default-profile-picture.jpg', upload_to='mediafiles/profile_images/'),
        ),
    ]
