# Generated by Django 3.2.12 on 2022-04-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/images/default-profile-picture.jpg', upload_to='profile_images/'),
        ),
    ]
