# Generated by Django 3.2.12 on 2022-04-05 16:28

import django.core.validators
from django.db import migrations, models
import movie_review_project.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1), movie_review_project.common.validators.validate_only_alphanumeric])),
                ('date_release', models.DateField()),
                ('genre', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(4), movie_review_project.common.validators.validate_only_letters])),
                ('movie_star_actors', models.TextField()),
                ('movie_rating', models.FloatField(validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(1)])),
                ('movie_description', models.TextField()),
                ('movie_cover', models.ImageField(upload_to='')),
            ],
        ),
    ]
