# Generated by Django 3.2.12 on 2022-04-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_star_actors',
            field=models.CharField(max_length=50),
        ),
    ]
