# Generated by Django 3.2.12 on 2022-04-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_movie_movie_star_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_description',
            field=models.CharField(max_length=100),
        ),
    ]
