# Generated by Django 3.2.12 on 2022-04-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_movie_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_cover',
            field=models.ImageField(default='staticfiles/images/default-movie-icon.jpg', upload_to='movie_covers/'),
        ),
    ]
