# Generated by Django 3.2.12 on 2022-04-26 17:50

import django.core.validators
from django.db import migrations, models
import movie_review_project.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_movie_movie_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(4), movie_review_project.common.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(max_length=50, validators=[movie_review_project.common.validators.validate_only_alphanumeric]),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='content',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
